version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: CGO_ENABLED=0 go test -v ./...

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"