// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package anndb_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Node struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterType((*Node)(nil), "anndb_pb.Node")
}

func init() {
	proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376)
}

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0x29, 0x2d,
	0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcc, 0xcb, 0x4b, 0x49,
	0x8a, 0x2f, 0x48, 0x92, 0xe2, 0x4a, 0xce, 0x2f, 0x4a, 0x85, 0x88, 0x2a, 0x19, 0x70, 0xb1, 0xf8,
	0xe5, 0xa7, 0xa4, 0x0a, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04,
	0x31, 0x65, 0xa6, 0x08, 0x49, 0x70, 0xb1, 0x27, 0xa6, 0xa4, 0x14, 0xa5, 0x16, 0x17, 0x4b, 0x30,
	0x29, 0x30, 0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x46, 0x85, 0x5c, 0x3c, 0x20, 0x1d, 0xc5, 0xbe, 0x89,
	0x79, 0x89, 0xe9, 0xa9, 0x45, 0x42, 0xda, 0x5c, 0xec, 0x8e, 0x29, 0x29, 0x10, 0x43, 0xf4, 0x60,
	0x76, 0xe8, 0x81, 0xf8, 0x52, 0x68, 0x7c, 0x03, 0x46, 0x21, 0x13, 0x2e, 0xae, 0xa0, 0xd4, 0xdc,
	0xfc, 0xb2, 0x54, 0xac, 0xea, 0xc5, 0x10, 0x7c, 0xd7, 0xdc, 0x82, 0x92, 0x4a, 0xdf, 0xd4, 0xe2,
	0xe2, 0xc4, 0xf4, 0xd4, 0x24, 0x36, 0xb0, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0f,
	0x03, 0x14, 0x9d, 0xd2, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NodesManagerClient is the client API for NodesManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodesManagerClient interface {
	AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (NodesManager_AddNodeClient, error)
	RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type nodesManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewNodesManagerClient(cc grpc.ClientConnInterface) NodesManagerClient {
	return &nodesManagerClient{cc}
}

func (c *nodesManagerClient) AddNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (NodesManager_AddNodeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_NodesManager_serviceDesc.Streams[0], "/anndb_pb.NodesManager/AddNode", opts...)
	if err != nil {
		return nil, err
	}
	x := &nodesManagerAddNodeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NodesManager_AddNodeClient interface {
	Recv() (*Node, error)
	grpc.ClientStream
}

type nodesManagerAddNodeClient struct {
	grpc.ClientStream
}

func (x *nodesManagerAddNodeClient) Recv() (*Node, error) {
	m := new(Node)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *nodesManagerClient) RemoveNode(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, "/anndb_pb.NodesManager/RemoveNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodesManagerServer is the server API for NodesManager service.
type NodesManagerServer interface {
	AddNode(*Node, NodesManager_AddNodeServer) error
	RemoveNode(context.Context, *Node) (*EmptyMessage, error)
}

// UnimplementedNodesManagerServer can be embedded to have forward compatible implementations.
type UnimplementedNodesManagerServer struct {
}

func (*UnimplementedNodesManagerServer) AddNode(req *Node, srv NodesManager_AddNodeServer) error {
	return status.Errorf(codes.Unimplemented, "method AddNode not implemented")
}
func (*UnimplementedNodesManagerServer) RemoveNode(ctx context.Context, req *Node) (*EmptyMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveNode not implemented")
}

func RegisterNodesManagerServer(s *grpc.Server, srv NodesManagerServer) {
	s.RegisterService(&_NodesManager_serviceDesc, srv)
}

func _NodesManager_AddNode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Node)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodesManagerServer).AddNode(m, &nodesManagerAddNodeServer{stream})
}

type NodesManager_AddNodeServer interface {
	Send(*Node) error
	grpc.ServerStream
}

type nodesManagerAddNodeServer struct {
	grpc.ServerStream
}

func (x *nodesManagerAddNodeServer) Send(m *Node) error {
	return x.ServerStream.SendMsg(m)
}

func _NodesManager_RemoveNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesManagerServer).RemoveNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anndb_pb.NodesManager/RemoveNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesManagerServer).RemoveNode(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodesManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anndb_pb.NodesManager",
	HandlerType: (*NodesManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RemoveNode",
			Handler:    _NodesManager_RemoveNode_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AddNode",
			Handler:       _NodesManager_AddNode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cluster.proto",
}
