// Code generated by protoc-gen-go. DO NOT EDIT.
// source: search.proto

package anndb_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest struct {
	Query                []float32 `protobuf:"fixed32,1,rep,packed,name=query,proto3" json:"query,omitempty"`
	K                    uint32    `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() []float32 {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *SearchRequest) GetK() uint32 {
	if m != nil {
		return m.K
	}
	return 0
}

type SearchResultItem struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score                float32  `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResultItem) Reset()         { *m = SearchResultItem{} }
func (m *SearchResultItem) String() string { return proto.CompactTextString(m) }
func (*SearchResultItem) ProtoMessage()    {}
func (*SearchResultItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_453745cff914010e, []int{1}
}

func (m *SearchResultItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResultItem.Unmarshal(m, b)
}
func (m *SearchResultItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResultItem.Marshal(b, m, deterministic)
}
func (m *SearchResultItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResultItem.Merge(m, src)
}
func (m *SearchResultItem) XXX_Size() int {
	return xxx_messageInfo_SearchResultItem.Size(m)
}
func (m *SearchResultItem) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResultItem.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResultItem proto.InternalMessageInfo

func (m *SearchResultItem) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SearchResultItem) GetScore() float32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "anndb_pb.SearchRequest")
	proto.RegisterType((*SearchResultItem)(nil), "anndb_pb.SearchResultItem")
}

func init() {
	proto.RegisterFile("search.proto", fileDescriptor_453745cff914010e)
}

var fileDescriptor_453745cff914010e = []byte{
	// 167 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x4e, 0x4d, 0x2c,
	0x4a, 0xce, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcc, 0xcb, 0x4b, 0x49, 0x8a,
	0x2f, 0x48, 0x52, 0x32, 0xe6, 0xe2, 0x0d, 0x06, 0xcb, 0x04, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0x89, 0x70, 0xb1, 0x16, 0x96, 0xa6, 0x16, 0x55, 0x4a, 0x30, 0x2a, 0x30, 0x6b, 0x30, 0x05,
	0x41, 0x38, 0x42, 0x3c, 0x5c, 0x8c, 0xd9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x8c, 0xd9,
	0x4a, 0x16, 0x5c, 0x02, 0x30, 0x4d, 0xc5, 0xa5, 0x39, 0x25, 0x9e, 0x25, 0xa9, 0xb9, 0x42, 0x7c,
	0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x2c, 0x41, 0x4c, 0x99, 0x29, 0x20, 0x73,
	0x8a, 0x93, 0xf3, 0x8b, 0x52, 0xc1, 0xba, 0x98, 0x82, 0x20, 0x1c, 0x23, 0x4f, 0x2e, 0x36, 0x88,
	0x4e, 0x21, 0x7b, 0x38, 0x4b, 0x5c, 0x0f, 0xe6, 0x1a, 0x3d, 0x14, 0xa7, 0x48, 0x49, 0x61, 0x4a,
	0xc0, 0xac, 0x33, 0x60, 0x4c, 0x62, 0x03, 0x7b, 0xc5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0e,
	0xf3, 0x43, 0x33, 0xda, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchClient is the client API for Search service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Search_SearchClient, error)
}

type searchClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchClient(cc grpc.ClientConnInterface) SearchClient {
	return &searchClient{cc}
}

func (c *searchClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (Search_SearchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Search_serviceDesc.Streams[0], "/anndb_pb.Search/Search", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Search_SearchClient interface {
	Recv() (*SearchResultItem, error)
	grpc.ClientStream
}

type searchSearchClient struct {
	grpc.ClientStream
}

func (x *searchSearchClient) Recv() (*SearchResultItem, error) {
	m := new(SearchResultItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServer is the server API for Search service.
type SearchServer interface {
	Search(*SearchRequest, Search_SearchServer) error
}

// UnimplementedSearchServer can be embedded to have forward compatible implementations.
type UnimplementedSearchServer struct {
}

func (*UnimplementedSearchServer) Search(req *SearchRequest, srv Search_SearchServer) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchServer(s *grpc.Server, srv SearchServer) {
	s.RegisterService(&_Search_serviceDesc, srv)
}

func _Search_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SearchServer).Search(m, &searchSearchServer{stream})
}

type Search_SearchServer interface {
	Send(*SearchResultItem) error
	grpc.ServerStream
}

type searchSearchServer struct {
	grpc.ServerStream
}

func (x *searchSearchServer) Send(m *SearchResultItem) error {
	return x.ServerStream.SendMsg(m)
}

var _Search_serviceDesc = grpc.ServiceDesc{
	ServiceName: "anndb_pb.Search",
	HandlerType: (*SearchServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Search_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "search.proto",
}
